args=commandArgs(T)
fqs=paste("/media/_EXTEND2/dingwubin/workdir/RNA_Seq/CirRNA/Project_luxiaojie_LncRNA/Project_luxiaojie_LncRNA_20140311_20140325/fastq/",args[1],c("_1.fastq","_2.fastq"),sep="")
sam=paste(args[1],".sam",sep="")
bam=paste(args[1],".bam",sep="")
sort.bam=paste(args[1],"_sort.bam",sep="")
gtf=paste("/media/_EXTend2016/zhangli/HCC-RNAseq/expr/",args[1],"/",args[1],".gtf",sep="")
mapping.cmd=paste("hisat2 -p 20 --dta -x /media/_EXTEND2/zhangli/NB/index/ucsc.gencode_tran  -1",fqs[1],"-2",fqs[2],"-S",sam)
cat(paste(mapping.cmd,"\n"))
system(mapping.cmd)
convert.cmd=paste("samtools view -@ 10 -bS",sam,">",bam)
cat(paste(convert.cmd,"\n"))
system(convert.cmd)
sort.cmd=paste("samtools sort -m 10G -@ 10",bam,gsub(".bam","",sort.bam))
cat(paste(sort.cmd,"\n"))
system(sort.cmd)
index.cmd=paste("samtools index",sort.bam)
cat(paste(index.cmd,"\n"))
system(index.cmd)
stringtie.cmd=paste("stringtie -e -B -p 8 -G /media/_EXTEND2/zhangli/NB/index/gencode.v19.annotation.gtf ","-o",gtf,sort.bam)
cat(paste(stringtie.cmd,"\n"))
system(stringtie.cmd)
